### ISSUE TITLE
no access to Server type

### ISSUE THREAD

**Issue by remituveri** [ducktors/fastify-socket.io#15]
Hi,

would it be possible to export 'socket.io' into the index.d.ts ?

`
import { FastifyPluginAsync } from 'fastify'
import * as SocketIO from 'socket.io'

declare module 'fastify' {
  interface FastifyInstance {
    io: SocketIO.Server
  }
}

export { SocketIO }
export const socketioServer: FastifyPluginAsync<Partial<SocketIO.ServerOptions>>
export default socketioServer
`

This way, it'll be possible to use that socket.io types in the application.

Thanks

**Comment by alemagio** [comment]
Hi I sugegst you to  `npm install --save-dev @types/socket.io`
The `Server` and any other socket.io type is provided by that package.

**Comment by remituveri** [comment]
Hi Alessandro,
The thing is `@types/socket.io` is deprecated and it says: "This is a stub types definition. socket.io provides its own type definitions, so you do not need this installed.".
Of course, it's possible to install `socket.io` to get the types, but your module (`fastify-socket.io`) already does that. This is why I suggested to export socket.io from your module.

Thanks

**Comment by alemagio** [comment]
You are right actually.
The thing is I don't think exporting the socket.io types is the ideal solution since I should export every type.
What I am planning to do with this and other plugins I maintain is to put `socket.io` as a `peerDependency`, this way the user will need to install it manually and will have access to all the types it exports.

If you want to open a PR feel free to do that I will be more than happy to review it. 😄

**Comment by alemagio** [comment]
I v3.0.0 `socket.io` is now a peer dependency, which means it is necessary to install it (which is a thing I should have done from the start). This way you can have access to any type directly from the package itself.
